name: "build"
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup development environment
        uses: ./.github/actions/setup-devenv

      - name: Build
        run: |
          source /opt/ros/jazzy/setup.bash
          cargo build --all-targets

      - name: Test
        run: |
          source /opt/ros/jazzy/setup.bash
          cargo test

      - name: Clippy
        run: |
          source /opt/ros/jazzy/setup.bash
          cargo clippy -- -D warnings
